start_climate:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_kia_hyundai
    climate:
      required: true
      example: true
      default: true
      selector:
        boolean:
    temperature:
      required: false
      example: 72
      default: 72
      selector:
        number:
          min: 62
          max: 82
          step: 1
          mode: box
          unit_of_measurement: Degrees
    defrost:
      required: true
      example: false
      default: false
      selector:
        boolean:
    heating:
      required: true
      example: false
      default: false
      selector:
        boolean:
    driver_seat:
      required: false
      example: 6
      selector:
        select:
          mode: dropdown
          options:
            - label: High Heat
              value: 6
            - label: Medium Heat
              value: 5
            - label: Low Heat
              value: 4
            - label: High Cool
              value: 3
            - label: Medium Cool
              value: 2
            - label: Low Cool
              value: 1
    passenger_seat:
      required: false
      example: 6
      selector:
        select:
          mode: dropdown
          options:
            - label: High Heat
              value: 6
            - label: Medium Heat
              value: 5
            - label: Low Heat
              value: 4
            - label: High Cool
              value: 3
            - label: Medium Cool
              value: 2
            - label: Low Cool
              value: 1
    left_rear_seat:
      required: false
      example: 6
      selector:
        select:
          mode: dropdown
          options:
            - label: High Heat
              value: 6
            - label: Medium Heat
              value: 5
            - label: Low Heat
              value: 4
            - label: High Cool
              value: 3
            - label: Medium Cool
              value: 2
            - label: Low Cool
              value: 1
    right_rear_seat:
      required: false
      example: 6
      selector:
        select:
          mode: dropdown
          options:
            - label: High Heat
              value: 6
            - label: Medium Heat
              value: 5
            - label: Low Heat
              value: 4
            - label: High Cool
              value: 3
            - label: Medium Cool
              value: 2
            - label: Low Cool
              value: 1
set_charge_limits:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_kia_hyundai
    dc_limit:
      required: true
      example: 50
      default: 90
      selector:
        number:
          min: 50
          max: 100
          step: 10
          unit_of_measurement: "%"
    ac_limit:
      required: true
      example: 50
      default: 90
      selector:
        number:
          min: 50
          max: 100
          step: 10
          unit_of_measurement: "%"