start_climate:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_kia_hyundai
    climate:
      required: true
      example: true
      default: true
      selector:
        boolean:
    temperature:
      required: false
      example: 72
      default: 72
      selector:
        number:
          min: 62
          max: 82
          step: 1
          mode: box
          unit_of_measurement: Degrees
    defrost:
      required: true
      example: false
      default: false
      selector:
        boolean:
    heating:
      required: true
      example: false
      default: false
      selector:
        boolean:
set_charge_limits:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: ha_kia_hyundai
    dc_limit:
      required: true
      example: 50
      default: 90
      selector:
        number:
          min: 50
          max: 100
          step: 10
          unit_of_measurement: "%"
    ac_limit:
      required: true
      example: 50
      default: 90
      selector:
        number:
          min: 50
          max: 100
          step: 10
          unit_of_measurement: "%"